### ISSUE TITLE
Bug in connecting to cluster in V.3.2.0

### ISSUE THREAD

**Issue by mehdidevopsyassir** [lensapp/lens#238]
**Describe the bug**
When i connect to cluster or try to enter setting it display a javascript error:
---
Uncaught Exception:
Error: spawn /Users/mehdi/Library/Application Support/Lens/binaries/kubectl/1.17.4/kubectl EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
---

**To Reproduce**
1. Click on connect or setting

**Comment by kuy** [comment]
Same here (v3.2.0 on macOS 10.14.6). I can access my cluster via `kubectl proxy` but not Lens.

Edit: Both v3.1.0 and v3.2.0-rc2 worked without connection errors. I'll stick to v3.2.0-rc2 until bugfix is released.

<img width="582" alt="Lens" src="https://user-images.githubusercontent.com/151614/79069862-84d73f80-7d0c-11ea-8cd3-0b5229d5b54d.png">

**Comment by josephtaylor** [comment]
Seeing this same error with v3.2.0 on linux mint 19.3

**Comment by walec51** [comment]
my Lens also stopped connecting to kubernetes after upgrade to 3.2.0 - Windows 10

**Comment by aderuelle** [comment]
Hi,

Ditto here on macOs 10.15.4, nothing displays inside main window :

<img width="359" alt="Capture d’écran 2020-04-15 à 08 26 29" src="https://user-images.githubusercontent.com/42127/79304999-d04b4280-7ef2-11ea-93c7-fa43a3c6fc8a.png">

Tried rolling back to 3.1.0 and removing `~/Library/Application Support/Lens` with no luck ...

Alexis

**Comment by walec51** [comment]
release 3.2.0 is broken - many people cannot connect to their clusters after the upgrade

downgrading to 3.1.0 solves the problem - does any one know how to turn off the automatic upgrader?

**Comment by walec51** [comment]
upgrading to 3.3.0-rc1: https://github.com/lensapp/lens/releases/tag/v3.3.0-rc.1

helped - I can now connect

**Comment by aderuelle** [comment]
> Hi,
> 
> Ditto here on macOs 10.15.4, nothing displays inside main window :
>
> Tried rolling back to 3.1.0 and removing `~/Library/Application Support/Lens` with no luck ...
> 
> Alexis

My problem isn't fixed in v3.3.0-rc1 : the main view remains black, I'll open another issue.

Thx

**Comment by jakolehm** [comment]
Should be fixed in v3.3.0.

**Comment by davydkov** [comment]
I've got the same error on `3.3.1`

**Comment by Itoktsnhc** [comment]
same error on 3.3.1 windows version
logs with  --enable-logging args
> [32minfo[39m: Checking for update
[24076:0427/101830.114:INFO:CONSOLE(17)] "update new lens", source: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/renderer.js (17)
[24076:0427/101830.114:INFO:CONSOLE(37)] "start vue", source: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/renderer.js (37)
[24076:0427/101830.163:INFO:CONSOLE(37)] "0", source: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/renderer.js (37)
[24076:0427/101830.187:INFO:CONSOLE(0)] "Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/fonts/MaterialIcons-Regular--iconfont.woff2", source: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/index.html#/ (0)
[32minfo[39m: Update for version 3.3.1 is not available (latest version: 3.3.1, downgrade is disallowed).
[24076:0427/101837.073:INFO:CONSOLE(17)] "VUEX: ACTION: REFINE CLUSTER", source: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/renderer.js (17)
(node:24076) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at env (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\webpack:\src\main\kube-auth-proxy.ts:54:17)
    at C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641406
    at Object.next (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641511)
    at a (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:640228)
(node:24076) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at env (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\webpack:\src\main\kube-auth-proxy.ts:54:17)
    at C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641406
    at Object.next (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:641511)
    at a (C:\Users\XXXX\AppData\Local\Programs\kontena-lens\resources\app.asar\main.js:1:640228)
(node:24076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[31merror[39m: Failed to connect to cluster bwntest: {"name":"RequestError","message":"Error: ESOCKETTIMEDOUT","cause":{"code":"ESOCKETTIMEDOUT","connect":false},"error":{"code":"ESOCKETTIMEDOUT","connect":false},"options":{"json":true,"timeout":10000,"headers":{"host":"4a010d12-a8f4-401b-876f-68165e9a952c.localhost:49152"},"uri":"http://127.0.0.1:49152/api-kube/version","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
[24076:0427/101847.095:INFO:CONSOLE(37)] "accessible watch, vals:", source: file:///C:/Users/XXXX/AppData/Local/Programs/kontena-lens/resources/app.asar/renderer.js (37)

**Comment by josephtaylor** [comment]
I'm still getting this exact `EACCESS` error and stack trace on linux with version 3.3.1
![Selection_088](https://user-images.githubusercontent.com/999191/81216444-84933280-8fa0-11ea-870a-8bf303e10fa1.png)

**Comment by darthchudi** [comment]
I have this issue as well on macOS with version 3.5.0
<img width="568" alt="Screenshot 2020-06-18 at 9 38 11 AM" src="https://user-images.githubusercontent.com/29544334/84998211-73187b00-b147-11ea-933a-dc93a6eacdf6.png">

**Comment by davydkov** [comment]
I fixed issue by removing bundled `kubectl` and put a symlink to the `kubectl` from the PATH

**Comment by Itoktsnhc** [comment]
On windows you can close lens first and delete all files and folders in the target folder:
C:\Users[username]\AppData\Roaming\Lens\binaries\kubectl .
Then open lens and waiting for the kubectl auto download finish, and hit reconnect.
